title: Council of Lórien
description: The Council of Lórien is dedicated to the Middle-earth Collectible Card Game (MECCG) by Iron Crown Enterprises
theme: just-the-docs

# url: "https://www.counciloflorien.com"
url: https://CouncilofLorien.github.io/test-col


#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
